# Auswertung der Parquet Dateien aus dem Echtzeitarchiv V14
- Start in /home/zvbn/python/rt2/run_rt2.sh jeweils 06:30

## Import der Module und Setzen Parameter

In [1]:
import pandas as pd
import sys
from dotenv import load_dotenv
import os
import datetime as dt
import calendar as cal

import shutil

from dotenv import dotenv_values
from redmine import delete_upload_dmsf
import logging
import glob

import openpyxl
from openpyxl import load_workbook
from openpyxl.styles import NamedStyle
from openpyxl.formatting.rule import ColorScaleRule, CellIsRule, FormulaRule

In [2]:
log_file = "log/log_rt.txt"
logging.basicConfig(filename=log_file, 
                        level=logging.INFO,
                        style="{",
                        format="{asctime} [{levelname:8}] {message}",
                        datefmt="%d.%m.%Y %H:%M:%S")

load_dotenv()

True

In [3]:
sys.path.append('/home/zvbn/python/rt2')

In [4]:
from class_rt_duck import RtDuck

In [5]:
logging.info("Auswertung RT aus parquet gestartet")

In [6]:
config = dotenv_values(".env")
#config

In [7]:
pd.options.display.max_columns = 100

In [8]:
jetzt = dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
gestern= (dt.date.today() - dt.timedelta(1)).strftime('%Y-%m-%d')
letzte07tage= (dt.date.today() - dt.timedelta(7)).strftime('%Y-%m-%d')
letzte14tage= (dt.date.today() - dt.timedelta(14)).strftime('%Y-%m-%d')
letzte21tage= (dt.date.today() - dt.timedelta(21)).strftime('%Y-%m-%d')

print(jetzt, letzte21tage)

2025-03-05 14:02:38 2025-02-12

## Funktionen

In [9]:
def replace_german_special_characters(text) -> str:
    replacements = {
        'ä': 'ae',
        'ö': 'oe',
        'ü': 'ue',
        'Ä': 'Ae',
        'Ö': 'Oe',
        'Ü': 'Ue',
        'ß': 'ss'
    }
    
    for german_char, replacement in replacements.items():
        text = text.replace(german_char, replacement)
    
    return text

In [10]:
#für die Formatierung der Ausgabe in html
func_proz = lambda s: str(int((1-s) * 1000)/10) + '%' if str(int(s)) != '-1' else '-'
func_date = lambda s: s.dt.strftime('%m/%d/%Y')

## CSS Styles

In [11]:
#Zellformatierung CSS
cell_hover = {  # for row hover use <tr> instead of <td>
    'selector': 'td:hover',
    'props': [('background-color', '#ffffb3')]
}
index_names = {
    'selector': '.index_name',
    'props': 'font-style: italic; color: darkgrey; font-weight:normal; font-family: sans-serif;'
}
headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: #FFFFFF; color: #000000; font-family: sans-serif;'
}

td = {'selector' : 'td', 'props': 'text-align:right; font-family: sans-serif'}

## Testen der class

In [12]:
rt = RtDuck()
rt

In [13]:
#Schließen der Verbindung
#rt.verbindung_schliessen()

In [14]:
rt.create_table_fahrten(server = 'prod')

Table 'fahrten' created.

In [15]:
rt.cursor.sql("from linien where linie like '5%' limit 30")

┌─────────┬──────────┬─────────┬────────────┬───────┐
│  linie  │ buendel  │  ebene  │    dlid    │  id   │
│ varchar │ varchar  │ varchar │  varchar   │ int32 │
├─────────┼──────────┼─────────┼────────────┼───────┤
│ 502     │ BHV      │ Stadt   │ de:VBN:502 │   101 │
│ 503     │ BHV      │ Stadt   │ de:VBN:503 │   254 │
│ 504     │ BHV      │ Stadt   │ de:VBN:504 │   418 │
│ 505     │ BHV      │ Stadt   │ de:VBN:505 │   102 │
│ 506     │ BHV      │ Stadt   │ de:VBN:506 │   255 │
│ 507     │ BHV      │ Stadt   │ de:VBN:507 │   103 │
│ 508     │ BHV      │ Stadt   │ de:VBN:508 │   104 │
│ 509     │ BHV      │ Stadt   │ de:VBN:509 │   105 │
│ 510     │ BHV      │ Stadt   │ de:VBN:510 │   419 │
│ 512     │ BHV      │ Stadt   │ de:VBN:512 │   106 │
│ ·       │  ·       │   ·     │     ·      │    ·  │
│ ·       │  ·       │   ·     │     ·      │    ·  │
│ ·       │  ·       │   ·     │     ·      │    ·  │
│ 58      │ HB Bus   │ Stadt   │ de:VBN:58  │   154 │
│ 5       │ HB Tram  │ Stadt   │ de:VBN:5   │    67 │
│ 550     │ TN 2 CUX │ NULL    │ de:VBN:550 │   318 │
│ 525     │ TN 5 CUX │ NULL    │ de:VBN:525 │   333 │
│ 529     │ TN 5 CUX │ NULL    │ de:VBN:529 │   717 │
│ 541     │ TN 5 CUX │ NULL    │ de:VBN:541 │   724 │
│ 542     │ TN 5 CUX │ NULL    │ de:VBN:542 │   718 │
│ 544     │ TN 5 CUX │ NULL    │ de:VBN:544 │   725 │
│ 545     │ TN 5 CUX │ NULL    │ de:VBN:545 │   719 │
│ 553     │ TN 5 CUX │ NULL    │ de:VBN:553 │   720 │
├─────────┴──────────┴─────────┴────────────┴───────┤
│ 30 rows (20 shown)                      5 columns │
└───────────────────────────────────────────────────┘

In [16]:
rt.create_table_zusatz(server = 'prod')
rt.create_table_verlauf(server = 'prod')
rt.create_table_matrix(server = 'prod')

Table 'zusatz' created.
Table 'verlauf' created.
Table 'matrix' created.

In [17]:
rt.cursor.sql("""select * 
              from zusatz 
              where datum = '2025-01-14' 
              and fahrtstarttime::text like '%06:15%'
              -- and destination like '%Bremen%'
              -- limit 5""").df()

,datum,fnr,destination,hasRealtime,vu,lineid,lineid_short,lineshort,reported_cancelled,journey_cancelled,ts_reported_cancelled,cancelled_kum,deviceid,clientid,journeyrttype,fahrtstarttime,fahrtstartstationname,fahrtstartstationdhid,fahrtendtime,fahrtendstationname,fahrtendstationdhid,realtimeHasEverBeenReported,filename
0,2025-01-14,7686608,Engter,True,Verkehrsgemeinschaft Osnabrück,de:VBN-VOS:686:1,de:VBN-VOS:686,686,False,False,,False,0114-9686608#!ADD!#vos#,vos,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Bramsche(Hase) Raschplatz,de:03459:12856::1,2025-01-14T06:27:00+01:00,Engter Post/Bei der Becke,de:03459:24947::1,True,out/parquet/prod/zusatz_2025_01_14.parquet
1,2025-01-14,,Borsigstraße (Mitte),True,Hamburger Hochbahn AG,de:hvv:260:,de:hvv:260,260,False,False,,False,0114-302861#!ADD!#HOCHBAHN-IDS#,HOCHBAHN-IDS,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Hamburg-Wandsbek U Markt,de:02000:60007:3:600126,2025-01-14T06:39:00+01:00,Hamburg Borsigstraße (Mitte),de:02000:61044::610060,True,out/parquet/prod/zusatz_2025_01_14.parquet
2,2025-01-14,,Rostock Südblick,True,Rostocker Straßenbahn AG,de:vmv-mbh:13003|24|60|0000026:,de:vmv-mbh:13003|24|60|0000026,26,False,False,,False,0114-11344-00021-1#!ADD!#RSAG#,RSAG,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Rostock Hauptbahnhof Süd,None,2025-01-14T06:37:00+01:00,Rostock Südblick,None,True,out/parquet/prod/zusatz_2025_01_14.parquet
3,2025-01-14,2948,Hamburg-Altona,True,None,ICE,ICE,ICE,False,False,,False,0114-2948-80-8000207-061500#!ADD!#DB#,DB,REALTIME_EXTRA_REPORTED,2025-01-14T06:15:00+01:00,Köln Hauptbahnhof,None,2025-01-14T10:04:00+01:00,Hamburg-Altona,de:02000:8002553:3:255305,True,out/parquet/prod/zusatz_2025_01_14.parquet
4,2025-01-14,,Hamburg-Altona,False,None,ICE,ICE,ICE,False,False,,False,0114-2948-80-8000207-061500#!ADD!#DB#,DB,REALTIME_EXTRA_REPORTED,2025-01-14T06:15:00+01:00,Köln Hauptbahnhof,None,2025-01-14T10:04:00+01:00,Hamburg-Altona,de:02000:8002553:3:255305,False,out/parquet/prod/zusatz_2025_01_14.parquet
5,2025-01-14,5,Breesen(b Neubrandenburg),True,Mecklenburg-Vorpommersche Verkehrsgesellschaft...,MVVG___101,MVVG___101,101,False,False,,False,0114-MAND_MVVG_LIN_101140125_-14206907#!ADD!#M...,MVVG,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Altentreptow ZOB,de:13071:3208:1:1,2025-01-14T06:54:00+01:00,Breesen(b Neubrandenburg),None,True,out/parquet/prod/zusatz_2025_01_14.parquet
6,2025-01-14,248,Bad Rothenfelde ZOB,True,Schrage Reisen,de:VBN-VOS:309:1,de:VBN-VOS:309,309,False,False,,False,0114-300337#!ADD!#vos#,vos,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Melle ZOB,de:03459:60362::D,2025-01-14T06:48:00+01:00,Bad Rothenfelde ZOB,de:03459:5774::1,True,out/parquet/prod/zusatz_2025_01_14.parquet
7,2025-01-14,140125,"Zarrentin, Bahnhofstraße",False,None,538,538,538,False,False,,False,0114-140125_VLP_538_1#!ADD!#VLP##!ADD!#NVBWSER...,VLP,REALTIME_EXTRA,2025-01-14T06:15:00+01:00,Boizenburg Markt,de:13076:4050,2025-01-14T06:57:00+01:00,"Zarrentin, Bahnhofstraße",de:13076:4330:1:2,False,out/parquet/prod/zusatz_2025_01_14.parquet
8,2025-01-14,,U Ohlstedt,True,Hamburger Hochbahn AG,de:hvv:276:,de:hvv:276,276,False,False,,False,0114-360211#!ADD!#HOCHBAHN-IDS#,HOCHBAHN-IDS,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Hamburg Mellingburgredder,de:02000:72026::720069,2025-01-14T06:52:00+01:00,Hamburg U Ohlstedt,de:02000:72052::720130,True,out/parquet/prod/zusatz_2025_01_14.parquet
9,2025-01-14,142,Holtenser Berg,True,Göttinger Verkehrsbetriebe (GöVB),de:VBN-VSN:11:,de:VBN-VSN:11,11,False,False,,False,0114-852006#!ADD!#goevb#,goevb,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Göttingen Grete-Henry-Straße,de:03152:33917::2,2025-01-14T06:54:00+01:00,Göttingen Europaallee,de:03159:33895::3,True,out/parquet/prod/zusatz_2025_01_14.parquet
10,2025-01-14,,"Zarrentin, Bahnhofstraße",False,None,538,538,538,False,False,,False,0114-140125_VLP_538_1#!ADD!#VLP##!ADD!#NVBWSER...,VLP,REALTIME_EXTRA,2025-01-14T06:15:00+01:00,Boizenburg Markt,de:13076:4050,2025-01-14T06:57:00+01:00,"Zarrentin, Bahnhofstraße",de:13076:4330:1:2,False,out/parquet/prod/zusatz_2025_01_14.parquet
11,2025-01-14,2400158,Hannover Paracelsusweg,True,üstra Hannoversche Verkehrsbetriebe AG,de:nds-gvh:gvh-3-135:,de:nds-gvh:gvh-3-135,135,False,False,,False,0114-14042001005001#!ADD!#ue#,ue,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Hannover Stöcken,None,2025-01-14T07:14:00+01:00,Hannover Paracelsusweg,None,True,out/parquet/prod/zusatz_2025_01_14.parquet
12,2025-01-14,340615,Norderstedt Mitte,True,Hamburger Hochbahn AG,de:hvv:U1:,de:hvv:U1,U1,False,False,,False,0114-340615#!ADD!#HOCHBAHN-IDS#,HOCHBAHN-IDS,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Hamburg-Ohlstedt,de:02000:72900:1:729000,2025-01-14T07:31:00+01:00,Norderstedt Mitte,de:01060:36961:1:369001,True,out/parquet/prod/zusatz_2025_01_14.parquet
13,2025-01-14,302,Bad Rothenfelde ZOB,True,Willy Hummert Omnibusverkehr GmbH,de:VBN-VOS:420:1,de:VBN-VOS:420,420,False,False,,False,0114-4420302#!ADD!#vos#,vos,DEVIATION_OF_SCHEDULED,2025-01-14T06:15:00+01:00,Dissen a.T.W. Industriestraße,de:03459:20647::3,2025-01-14T06:27:00+01:00,Bad Rothenfelde ZOB,de:03459:5774::C,True,out/parquet/prod/zusatz_2025_01_14.parquet

In [18]:
rt.cursor.sql("select lineid, lineid_short, * from fahrten where datum::date = '2025-01-28' and lineid like 'de:VBN:740%' order by fnr")

┌──────────────┬──────────────┬─────────────────────┬─────────┬─────────────────────┬─────────────┬───────────────────────────────────────┬──────────────┬──────────────┬───────────┬────────────────────┬───────────────────┬───────────────────────┬───────────────┬────────────────────────────────────────┬──────────┬───────────────┬───────────────────────────┬───────────────────────────────────┬───────────────────────┬───────────────────────────┬────────────────────────────────┬─────────────────────┬─────────────────────────────┬─────────────────────────────────────────────┐
│    lineid    │ lineid_short │        datum        │   fnr   │     destination     │ hasRealtime │                  vu                   │    lineid    │ lineid_short │ lineshort │ reported_cancelled │ journey_cancelled │ ts_reported_cancelled │ cancelled_kum │                deviceid                │ clientid │ journeyrttype │      fahrtstarttime       │       fahrtstartstationname       │ fahrtstartstationdhid │       fahrtendtime        │      fahrtendstationname       │ fahrtendstationdhid │ realtimeHasEverBeenReported │                  filename                   │
│   varchar    │   varchar    │    timestamp_ns     │ varchar │       varchar       │   boolean   │                varchar                │   varchar    │   varchar    │  varchar  │      boolean       │      boolean      │        varchar        │    boolean    │                varchar                 │ varchar  │    varchar    │          varchar          │              varchar              │        varchar        │          varchar          │            varchar             │       varchar       │           boolean           │                   varchar                   │
├──────────────┼──────────────┼─────────────────────┼─────────┼─────────────────────┼─────────────┼───────────────────────────────────────┼──────────────┼──────────────┼───────────┼────────────────────┼───────────────────┼───────────────────────┼───────────────┼────────────────────────────────────────┼──────────┼───────────────┼───────────────────────────┼───────────────────────────────────┼───────────────────────┼───────────────────────────┼────────────────────────────────┼─────────────────────┼─────────────────────────────┼─────────────────────────────────────────────┤
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740001 │ Verden (Aller)      │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740001-8004920400000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T05:46:00+01:00 │ Achim(b Bremen) Bahnhof Nord      │ de:03361:649::1       │ 2025-01-28T06:25:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::4   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740002 │ Bremen Hbf          │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740002-8004922400000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T04:22:00+01:00 │ Verden(Aller) ZOB                 │ de:03361:93709::4     │ 2025-01-28T05:47:00+01:00 │ Bremen Hauptbahnhof            │ de:04011:13925::H   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740004 │ Bremen-Sebaldsbrück │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740004-8004922500000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T05:39:00+01:00 │ Verden(Aller) ZOB                 │ de:03361:93709::4     │ 2025-01-28T06:47:00+01:00 │ Bremen Sebaldsbrück (Bus+Tram) │ de:04011:14184::2   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740005 │ Verden (Aller)      │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740005-8004921100000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T07:05:00+01:00 │ Etelsen Bremer Straße             │ de:03361:26093::1     │ 2025-01-28T07:33:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::4   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:1 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740006 │ Bremen Hauptbahnhof │ true        │ Reisedienst von Rahden GmbH & Co. KG  │ de:VBN:740:1 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740006#!ADD!#vrahden#            │ vrahden  │ SCHEDULED     │ 2025-01-28T06:20:00+01:00 │ Baden(Achim) Bahnhof Nord         │ de:03361:9012342::2   │ 2025-01-28T07:21:00+01:00 │ Bremen Hauptbahnhof            │ de:04011:13925::H   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740007 │ Verden (Aller)      │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740007-8004920600000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T06:08:00+01:00 │ Bremen Hauptbahnhof               │ de:04011:13925::H     │ 2025-01-28T07:44:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::4   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:1 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740009 │ Verden(Aller) ZOB   │ true        │ Reisedienst von Rahden GmbH & Co. KG  │ de:VBN:740:1 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740009#!ADD!#vrahden#            │ vrahden  │ SCHEDULED     │ 2025-01-28T06:36:00+01:00 │ Uphusen(Achim) Arenkamp           │ de:03361:92750::1     │ 2025-01-28T07:36:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::5   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:1 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740011 │ Achim Bf            │ true        │ Reisedienst von Rahden GmbH & Co. KG  │ de:VBN:740:1 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740011#!ADD!#vrahden#            │ vrahden  │ SCHEDULED     │ 2025-01-28T06:35:00+01:00 │ Uphusen(Achim) Uphuser Heerstraße │ de:03361:92759::1     │ 2025-01-28T06:54:00+01:00 │ Achim(b Bremen) Bahnhof Nord   │ de:03361:649::1     │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:1 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740013 │ Verden(Aller) ZOB   │ true        │ Reisedienst von Rahden GmbH & Co. KG  │ de:VBN:740:1 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740013#!ADD!#vrahden#            │ vrahden  │ SCHEDULED     │ 2025-01-28T06:50:00+01:00 │ Bremen Bf Mahndorf                │ de:04011:13765::1     │ 2025-01-28T08:06:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::5   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740015 │ Verden-Dauelsen     │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740015-8004920900000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T06:50:00+01:00 │ Bremen Bf Mahndorf                │ de:04011:13765::E     │ 2025-01-28T07:47:00+01:00 │ Dauelsen Berufsschulzentrum    │ de:03361:19142::1   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│      ·       │     ·        │          ·          │    ·    │       ·             │  ·          │                   ·                   │      ·       │     ·        │  ·        │   ·                │   ·               │           ·           │   ·           │                   ·                    │ ·        │     ·         │             ·             │        ·                          │         ·             │             ·             │         ·                      │         ·           │  ·                          │                      ·                      │
│      ·       │     ·        │          ·          │    ·    │       ·             │  ·          │                   ·                   │      ·       │     ·        │  ·        │   ·                │   ·               │           ·           │   ·           │                   ·                    │ ·        │     ·         │             ·             │        ·                          │         ·             │             ·             │         ·                      │         ·           │  ·                          │                      ·                      │
│      ·       │     ·        │          ·          │    ·    │       ·             │  ·          │                   ·                   │      ·       │     ·        │  ·        │   ·                │   ·               │           ·           │   ·           │                   ·                    │ ·        │     ·         │             ·             │        ·                          │         ·             │             ·             │         ·                      │         ·           │  ·                          │                      ·                      │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740447 │ Verden (Aller)      │ false       │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │                                        │ -        │ SCHEDULED     │ 2025-01-28T15:00:00+01:00 │ Bremen Weserpark                  │ de:04011:14282::3     │ 2025-01-28T15:59:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::4   │ false                       │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740451 │ Daverden            │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740451-8004921500000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T16:00:00+01:00 │ Bremen Hauptbahnhof               │ de:04011:13925::H     │ 2025-01-28T17:17:00+01:00 │ Daverden Suhrfeldstraße        │ de:03361:19200::2   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740457 │ Verden (Aller)      │ false       │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │                                        │ -        │ SCHEDULED     │ 2025-01-28T18:00:00+01:00 │ Bremen Weserpark                  │ de:04011:14282::3     │ 2025-01-28T18:59:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::4   │ false                       │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740460 │ Bremen-Weserpark    │ false       │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │                                        │ -        │ SCHEDULED     │ 2025-01-28T16:44:00+01:00 │ Verden(Aller) ZOB                 │ de:03361:93709::4     │ 2025-01-28T17:43:00+01:00 │ Bremen Weserpark               │ de:04011:14282::4   │ false                       │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740462 │ Bremen-Weserpark    │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740462-8004922800000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T17:44:00+01:00 │ Verden(Aller) ZOB                 │ de:03361:93709::4     │ 2025-01-28T18:44:00+01:00 │ Bremen Weserpark               │ de:04011:14282::4   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740464 │ Bremen Hbf          │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740464-8004923502000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T18:23:00+01:00 │ Baden(Achim) Bahnhof              │ de:03361:6472::1      │ 2025-01-28T19:24:00+01:00 │ Bremen Hauptbahnhof            │ de:04011:13925::H   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740468 │ Bremen-Weserpark    │ false       │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │                                        │ -        │ SCHEDULED     │ 2025-01-28T19:44:00+01:00 │ Verden(Aller) ZOB                 │ de:03361:93709::4     │ 2025-01-28T20:43:00+01:00 │ Bremen Weserpark               │ de:04011:14282::4   │ false                       │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:1 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740730 │ Bremen Hauptbahnhof │ true        │ Reisedienst von Rahden GmbH & Co. KG  │ de:VBN:740:1 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740730#!ADD!#vrahden#            │ vrahden  │ SCHEDULED     │ 2025-01-28T12:23:00+01:00 │ Baden(Achim) Bahnhof Nord         │ de:03361:9012342::2   │ 2025-01-28T13:29:00+01:00 │ Bremen Hauptbahnhof            │ de:04011:13925::H   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:2 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740749 │ Verden (Aller)      │ true        │ Weser-Ems-Bus Auftragnehmerleistungen │ de:VBN:740:2 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740749-8004920100000#!ADD!#DBRB# │ DBRB     │ SCHEDULED     │ 2025-01-28T16:00:00+01:00 │ Bremen Weserpark                  │ de:04011:14282::3     │ 2025-01-28T17:02:00+01:00 │ Verden(Aller) ZOB              │ de:03361:93709::4   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
│ de:VBN:740:1 │ de:VBN:740   │ 2025-01-28 00:00:00 │ 1740758 │ Bremen Hauptbahnhof │ true        │ Reisedienst von Rahden GmbH & Co. KG  │ de:VBN:740:1 │ de:VBN:740   │ 740       │ false              │ false             │                       │ false         │ 0128-1740758#!ADD!#vrahden#            │ vrahden  │ SCHEDULED     │ 2025-01-28T16:23:00+01:00 │ Baden(Achim) Bahnhof Nord         │ de:03361:9012342::2   │ 2025-01-28T17:24:00+01:00 │ Bremen Hauptbahnhof            │ de:04011:13925::H   │ true                        │ out/parquet/prod/fahrten_2025_01_28.parquet │
├──────────────┴──────────────┴─────────────────────┴─────────┴─────────────────────┴─────────────┴───────────────────────────────────────┴──────────────┴──────────────┴───────────┴────────────────────┴───────────────────┴───────────────────────┴───────────────┴────────────────────────────────────────┴──────────┴───────────────┴───────────────────────────┴───────────────────────────────────┴───────────────────────┴───────────────────────────┴────────────────────────────────┴─────────────────────┴─────────────────────────────┴─────────────────────────────────────────────┤
│ 68 rows (20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 25 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## Erstellen einer Auswertung mit abweichender Clientid

In [19]:
rt.cursor.sql("from fahrten limit 3")

┌─────────────────────┬─────────┬─────────────┬─────────────┬───────────────────────┬─────────────┬──────────────┬───────────┬────────────────────┬───────────────────┬───────────────────────┬───────────────┬─────────────────────────────────┬──────────┬───────────────┬───────────────────────────┬──────────────────────────┬───────────────────────┬───────────────────────────┬──────────────────────┬─────────────────────┬─────────────────────────────┬─────────────────────────────────────────────┐
│        datum        │   fnr   │ destination │ hasRealtime │          vu           │   lineid    │ lineid_short │ lineshort │ reported_cancelled │ journey_cancelled │ ts_reported_cancelled │ cancelled_kum │            deviceid             │ clientid │ journeyrttype │      fahrtstarttime       │  fahrtstartstationname   │ fahrtstartstationdhid │       fahrtendtime        │ fahrtendstationname  │ fahrtendstationdhid │ realtimeHasEverBeenReported │                  filename                   │
│    timestamp_ns     │ varchar │   varchar   │   boolean   │        varchar        │   varchar   │   varchar    │  varchar  │      boolean       │      boolean      │        varchar        │    boolean    │             varchar             │ varchar  │    varchar    │          varchar          │         varchar          │        varchar        │          varchar          │       varchar        │       varchar       │           boolean           │                   varchar                   │
├─────────────────────┼─────────┼─────────────┼─────────────┼───────────────────────┼─────────────┼──────────────┼───────────┼────────────────────┼───────────────────┼───────────────────────┼───────────────┼─────────────────────────────────┼──────────┼───────────────┼───────────────────────────┼──────────────────────────┼───────────────────────┼───────────────────────────┼──────────────────────┼─────────────────────┼─────────────────────────────┼─────────────────────────────────────────────┤
│ 2024-08-29 00:00:00 │ 6737    │ Huchting    │ true        │ Bremer Straßenbahn AG │ de:VBN:N1:  │ de:VBN:N1    │ N1        │ false              │ false             │                       │ false         │ 0829-395018-00018-1#!ADD!#BSAG# │ BSAG     │ SCHEDULED     │ 2024-08-29T03:58:00+02:00 │ Bremen Solinger Straße   │ de:04011:14197::4     │ 2024-08-29T04:04:00+02:00 │ Bremen Roland-Center │ de:04011:14155::2   │ NULL                        │ out/parquet/prod/fahrten_2024_08_29.parquet │
│ 2024-08-29 00:00:00 │ 2659    │ Lilienthal  │ true        │ Bremer Straßenbahn AG │ de:VBN:4:   │ de:VBN:4     │ 4         │ false              │ false             │                       │ false         │ 0829-969018-00018-1#!ADD!#BSAG# │ BSAG     │ SCHEDULED     │ 2024-08-29T03:22:00+02:00 │ Bremen Kurt-Huber-Straße │ de:04011:14024::2     │ 2024-08-29T04:02:00+02:00 │ Lilienthal           │ de:03356:55728::1   │ NULL                        │ out/parquet/prod/fahrten_2024_08_29.parquet │
│ 2024-08-29 00:00:00 │ 1531    │ Imsum Ort   │ false       │ BREMERHAVEN BUS       │ de:VBN:509: │ de:VBN:509   │ 509       │ false              │ false             │                       │ false         │                                 │ -        │ SCHEDULED     │ 2024-08-29T00:52:00+02:00 │ Bremerhaven Alte Kirche  │ de:04012:14336::2     │ 2024-08-29T01:09:00+02:00 │ Imsum Ort            │ de:03352:46241::1   │ NULL                        │ out/parquet/prod/fahrten_2024_08_29.parquet │
└─────────────────────┴─────────┴─────────────┴─────────────┴───────────────────────┴─────────────┴──────────────┴───────────┴────────────────────┴───────────────────┴───────────────────────┴───────────────┴─────────────────────────────────┴──────────┴───────────────┴───────────────────────────┴──────────────────────────┴───────────────────────┴───────────────────────────┴──────────────────────┴─────────────────────┴─────────────────────────────┴─────────────────────────────────────────────┘

In [20]:
df_line_clientid = rt.cursor.sql("""select distinct lineid_short, vu, clientid, 
                                 min(datum)::date::text as min_datum,
                                 max(datum)::date::text as max_datum,
                                 count(datum) as anzahl,
                                 count(*) filter (where reported_cancelled  = true) as anzahl_reported_cancelled,
                                 count(*) filter (where journey_cancelled  = true) as anzahl_journey_cancelled
                                 from fahrten 
                                 where datum >= (current_date - interval 7 day) 
                                 group by all
                                 order by  max_datum desc, lineid_short""").df()

In [21]:
df_line_clientid

,lineid_short,vu,clientid,min_datum,max_datum,anzahl,anzahl_reported_cancelled,anzahl_journey_cancelled
0,de:VBN-VGC:910,SBV Janßen GmbH & Co. KG,janssen,2025-02-26,2025-03-04,100,0,0
1,de:VBN:1,Bremer Straßenbahn AG,BSAG,2025-02-26,2025-03-04,1488,7,0
2,de:VBN:10,Bremer Straßenbahn AG,BSAG,2025-02-26,2025-03-04,1320,9,2
3,de:VBN:101,Verkehrsbetriebe Oldenburger Land,IVU-Regio,2025-02-26,2025-03-04,174,0,0
4,de:VBN:102,Verkehrsbetriebe Grafschaft Hoya GmbH,IVU-Regio,2025-02-26,2025-03-04,67,0,0
...,...,...,...,...,...,...,...,...
963,de:VBN:N4,Bremer Straßenbahn AG,-,2025-02-26,2025-02-26,1,1,0
964,de:VBN:N5,Bremer Straßenbahn AG,-,2025-02-26,2025-02-26,1,1,1
965,de:VBN:N6,Bremer Straßenbahn AG,-,2025-02-26,2025-02-26,2,2,0
966,de:VBN:N9,Bremer Straßenbahn AG,-,2025-02-26,2025-02-26,1,1,1
967,de:VBN:RB61,eurobahn,bsvg,2025-02-26,2025-02-26,5,0,0

In [22]:
# Export DataFrame to Excel
excel_file = '/var/www/rt_archiv/line_clientid.xlsx'
df_line_clientid.to_excel(excel_file, index=False, sheet_name='Sheet1')

# Load the workbook and select the active worksheet
wb = load_workbook(excel_file)
ws = wb.active

# Apply autofilter
ws.auto_filter.ref = ws.dimensions

# Freeze the first row
ws.freeze_panes = 'A2'

#Anpasssung der Spaltenbreite
ws.column_dimensions['A'].width = 20

ws.column_dimensions['B'].width = 30
ws.column_dimensions['C'].width = 20
ws.column_dimensions['D'].width = 20
ws.column_dimensions['E'].width = 20
ws.column_dimensions['F'].width = 20
ws.column_dimensions['G'].width = 20
ws.column_dimensions['H'].width = 20

# Save the workbook
wb.save(excel_file)

In [23]:
rt.cursor.sql("describe fahrten").df()

                    column_name   column_type null   key default extra
0                         datum  TIMESTAMP_NS  YES  None    None  None
1                           fnr       VARCHAR  YES  None    None  None
2                   destination       VARCHAR  YES  None    None  None
3                   hasRealtime       BOOLEAN  YES  None    None  None
4                            vu       VARCHAR  YES  None    None  None
5                        lineid       VARCHAR  YES  None    None  None
6                  lineid_short       VARCHAR  YES  None    None  None
7                     lineshort       VARCHAR  YES  None    None  None
8            reported_cancelled       BOOLEAN  YES  None    None  None
9             journey_cancelled       BOOLEAN  YES  None    None  None
10        ts_reported_cancelled       VARCHAR  YES  None    None  None
11                cancelled_kum       BOOLEAN  YES  None    None  None
12                     deviceid       VARCHAR  YES  None    None  None
13                     clientid       VARCHAR  YES  None    None  None
14                journeyrttype       VARCHAR  YES  None    None  None
15               fahrtstarttime       VARCHAR  YES  None    None  None
16        fahrtstartstationname       VARCHAR  YES  None    None  None
17        fahrtstartstationdhid       VARCHAR  YES  None    None  None
18                 fahrtendtime       VARCHAR  YES  None    None  None
19          fahrtendstationname       VARCHAR  YES  None    None  None
20          fahrtendstationdhid       VARCHAR  YES  None    None  None
21  realtimeHasEverBeenReported       BOOLEAN  YES  None    None  None
22                     filename       VARCHAR  YES  None    None  None

In [24]:
df_linien_nach_client = rt.cursor.sql( """select f.lineid_short, datum::date as datum, buendel, vu, clientid,
                round((count (*) filter (realtimeHasEverBeenReported = true) / count(*) ) * 100, 1) as anteil_ez  
              from fahrten f 
                join linien l on f.lineid_short = l.dlid 
              
              where datum::date > (current_date - interval 7 day)
              group by all""").df()

## Erstellen der Statistiken log_12_pivot und log_3_pivot

In [25]:
def sql_ebenen(ebenen):
            sql = f""" 
              select datum::date::text as datum, buendel, 
                round((count (*) filter (realtimeHasEverBeenReported = true) / count(*) ) * 100, 1) as anteil_ez  
              from fahrten f 
                join linien l on f.lineid_short = l.dlid 
              where 
                f.datum > (current_date - interval 60 day)
              and ebene in {ebenen}
              group by all"""
            
            return sql

### HTML Stil

In [26]:
#Zellformatierung CSS
cell_hover = {  # for row hover use <tr> instead of <td>
    'selector': 'td:hover',
    'props': [('background-color', '#ffffb3')]
}
index_names = {
    'selector': '.index_name',
    'props': 'font-style: italic; color: darkgrey; font-weight:normal; font-family: sans-serif;'
}
headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: #FFFFFF; color: #000000; font-family: sans-serif;'
}

td = {'selector' : 'td', 'props': 'text-align:right; font-family: sans-serif'}

In [27]:
ebenen = ('1+', '1', '2', 'Stadt', 'Nacht')
df = rt.cursor.sql(sql_ebenen(ebenen=ebenen)).df()
df_pivot = df.pivot(index='datum', columns='buendel', values='anteil_ez')
df_pivot.sort_values('datum', ascending=False).style.background_gradient(cmap="RdYlGn", axis = None,  vmin=0.0, vmax=95)\
    .highlight_null(color='white').format(formatter = '{:.1f}%', precision=1, na_rep='-', thousands=" ", decimal= ',').set_table_styles([index_names, headers, td])\
        .to_html('/var/www/rt_archiv/log_12_pivot.html', encoding='LATIN1')

In [28]:
ebenen = "('3')"
df = rt.cursor.sql(sql_ebenen(ebenen=ebenen)).df()
df_pivot = df.pivot(index='datum', columns='buendel', values='anteil_ez')
df_pivot.sort_values('datum', ascending=False).style.background_gradient(cmap="RdYlGn", axis = None,  vmin=0.0, vmax=95)\
    .highlight_null(color='white').format(formatter = '{:.1f}%', precision=1, na_rep='-', thousands=" ", decimal= ',').set_table_styles([index_names, headers, td])\
        .to_html('/var/www/rt_archiv/log_3_pivot.html', encoding='LATIN1')

In [29]:
rt.anzahl_fahrten_betreiber()

In [30]:
rt.anzahl_fahrten_betreiber().to_html('/var/www/rt_archiv/anzahl_fahrten_betreiber.html', encoding='LATIN1')

## Ermitteln der Fahrten, die nur 0 Min senden bzw. im Verlauf nur 0 gespeichert wurde

In [31]:
rt.cursor.sql(""" select * from
                (select ex_lineid, fnr,min(operday) as start, max(operday) as ende ,count(*) as count from (
                    select * from 
                        (select operday, ex_lineid, fnr, avg(dep_del) as avg_del
                        from verlauf 
                        where dep_del is not null
                        and has_rt = true
                        group by all)
                    where avg_del = 0 and ex_lineid like 'de:VBN:6__:%' and operday > (current_date - interval 28 day)
                    order by ex_lineid)               
                
                group by all
                order by count desc)
              where count > 3
              """).df()

        ex_lineid      fnr      start       ende  count
0    de:VBN:641:1  1641027 2025-02-07 2025-03-04     17
1    de:VBN:641:1  1641013 2025-02-07 2025-03-03     15
2     de:VBN:617:  1617008 2025-02-07 2025-03-04     15
3     de:VBN:651:  1651301 2025-02-06 2025-03-03     14
4     de:VBN:611:  1611005 2025-02-06 2025-03-04     14
..            ...      ...        ...        ...    ...
171  de:VBN:63S:1     7136 2025-02-12 2025-02-20      4
172  de:VBN:63S:1     7132 2025-02-06 2025-02-20      4
173  de:VBN:668:1  1668009 2025-02-10 2025-02-27      4
174   de:VBN:670:  1670021 2025-02-12 2025-02-28      4
175  de:VBN:681:1  1681704 2025-02-06 2025-02-20      4

[176 rows x 5 columns]

In [32]:
rt.cursor.sql("select * from verlauf where fnr = '1630018'").df().to_excel('out/verlauf_1630018.xlsx', index=False)

In [33]:
suffix = 'mitte'
#auswahl_linien = '680|660|N68'
auswahl_linien = '630|670|N63|N67'

df_auswahl_ohne_rt = rt.cursor.sql(f"""select * from
              (select lineshort, min(datum)::date as min_datum, max(datum)::date as max_datum, fnr, 
              count(* ) as anzahl, 
              count(* ) filter (hasRealtime  = false ) as anzahl_ohne_rt, 
              anzahl_ohne_rt / count(* ) as proz_ohne_rt
              from fahrten  
              where lineid  SIMILAR TO '.*({auswahl_linien}).*' 
              -- and hasRealtime  = false 
              and datum  >= (current_date() - interval 28 days)
              group by all
              )
              where anzahl_ohne_rt > 1
              order by proz_ohne_rt desc

              -- limit 10""").df()

df_zusatz = rt.cursor.sql(f"""select * from zusatz where lineid  SIMILAR TO 'de:VBN:.*({auswahl_linien}).*' """).df()

ohne_rt_xl = f"out/rt_ohne_realtime_{suffix}.xlsx"
sn01 = 'ohne_rt'
with pd.ExcelWriter(ohne_rt_xl, engine='openpyxl') as writer:
    df_auswahl_ohne_rt.to_excel(writer, sheet_name=sn01, index=False)
    worksheet = writer.sheets[sn01]
    worksheet.freeze_panes = 'a2'

    worksheet.column_dimensions['B'].width = 15
    worksheet.column_dimensions['C'].width = 15
    worksheet.auto_filter.ref = worksheet.dimensions

    # Format the 'Zeit' column as date
    for cell in worksheet['B']:  # Assuming 'Zeit' is in column D
        if cell.row == 1:  # Skip the header row
            continue
        cell.number_format = 'YYYY-MM-DD'

    # Format the 'Zeit' column as date
    for cell in worksheet['C']:  # Assuming 'Zeit' is in column D
        if cell.row == 1:  # Skip the header row
            continue
        cell.number_format = 'YYYY-MM-DD'

    # Format the 'Prozent' column as percentage
    for cell in worksheet['G']:  # Assuming 'Prozent' is in column D
        if cell.row == 1:  # Skip the header row
            continue
        cell.number_format = '0.0%'
 
df_zusatz

,datum,fnr,destination,hasRealtime,vu,lineid,lineid_short,lineshort,reported_cancelled,journey_cancelled,ts_reported_cancelled,cancelled_kum,deviceid,clientid,journeyrttype,fahrtstarttime,fahrtstartstationname,fahrtstartstationdhid,fahrtendtime,fahrtendstationname,fahrtendstationdhid,realtimeHasEverBeenReported,filename
0,2024-09-01,1630226,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0901-1630226#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-01T20:00:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-01T21:29:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,NaN,out/parquet/prod/zusatz_2024_09_01.parquet
1,2024-09-02,1630054,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0902-1630054#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-02T18:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-02T19:56:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,NaN,out/parquet/prod/zusatz_2024_09_02.parquet
2,2024-09-02,1630058,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0902-1630058#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-02T20:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-02T21:43:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,NaN,out/parquet/prod/zusatz_2024_09_02.parquet
3,2024-09-09,1630054,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0909-1630054#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-09T18:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-09T19:56:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,False,out/parquet/prod/zusatz_2024_09_09.parquet
4,2024-09-09,1630058,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0909-1630058#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-09T20:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-09T21:43:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,False,out/parquet/prod/zusatz_2024_09_09.parquet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,2025-02-26,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0226-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-02-26T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-02-26T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_02_26.parquet
323,2025-02-27,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0227-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-02-27T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-02-27T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_02_27.parquet
324,2025-02-28,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0228-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-02-28T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-02-28T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_02_28.parquet
325,2025-03-03,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0303-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-03-03T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-03-03T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_03_03.parquet
326,2025-03-04,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0304-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-03-04T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-03-04T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_03_04.parquet

In [34]:
df_linien_quote_rt = rt.cursor.sql("""
            select * from
              ( select lineshort, min(datum)::date as min_datum, max(datum)::date as max_datum,  
                    count(* ) as anzahl, 
                    count(* ) filter (hasRealtime  = false ) as anzahl_ohne_rt, 
                    anzahl_ohne_rt / count(* ) as proz_ohne_rt
                from fahrten  
                where 
                -- and hasRealtime  = false 
                    datum  >= (current_date() - interval 28 days)
                group by all
              )
              where anzahl_ohne_rt > 1
              order by proz_ohne_rt desc

              -- limit 10""").df()

df_linien_quote_rt

    lineshort  min_datum  max_datum  anzahl  anzahl_ohne_rt  proz_ohne_rt
0         116 2025-02-05 2025-03-04     301             301      1.000000
1         863 2025-02-05 2025-03-04     100             100      1.000000
2          48 2025-02-05 2025-03-04    1000            1000      1.000000
3         399 2025-02-05 2025-03-04     100             100      1.000000
4         263 2025-02-05 2025-03-04     132             132      1.000000
..        ...        ...        ...     ...             ...           ...
604       322 2025-02-05 2025-03-04    3076               7      0.002276
605       323 2025-02-05 2025-03-04    3079               7      0.002273
606       505 2025-02-05 2025-03-04    1855               4      0.002156
607       750 2025-02-05 2025-03-04     940               2      0.002128
608       503 2025-02-05 2025-03-04    1988               4      0.002012

[609 rows x 6 columns]

In [35]:
df_zusatz

,datum,fnr,destination,hasRealtime,vu,lineid,lineid_short,lineshort,reported_cancelled,journey_cancelled,ts_reported_cancelled,cancelled_kum,deviceid,clientid,journeyrttype,fahrtstarttime,fahrtstartstationname,fahrtstartstationdhid,fahrtendtime,fahrtendstationname,fahrtendstationdhid,realtimeHasEverBeenReported,filename
0,2024-09-01,1630226,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0901-1630226#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-01T20:00:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-01T21:29:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,NaN,out/parquet/prod/zusatz_2024_09_01.parquet
1,2024-09-02,1630054,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0902-1630054#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-02T18:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-02T19:56:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,NaN,out/parquet/prod/zusatz_2024_09_02.parquet
2,2024-09-02,1630058,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0902-1630058#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-02T20:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-02T21:43:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,NaN,out/parquet/prod/zusatz_2024_09_02.parquet
3,2024-09-09,1630054,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0909-1630054#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-09T18:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-09T19:56:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,False,out/parquet/prod/zusatz_2024_09_09.parquet
4,2024-09-09,1630058,Zeven Bahnhof Süd,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0909-1630058#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2024-09-09T20:20:00+02:00,Bremen Hauptbahnhof,de:04011:13925::G,2024-09-09T21:43:00+02:00,Zeven Bahnhof Süd,de:03357:102760::7,False,out/parquet/prod/zusatz_2024_09_09.parquet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,2025-02-26,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0226-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-02-26T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-02-26T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_02_26.parquet
323,2025-02-27,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0227-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-02-27T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-02-27T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_02_27.parquet
324,2025-02-28,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0228-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-02-28T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-02-28T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_02_28.parquet
325,2025-03-03,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0303-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-03-03T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-03-03T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_03_03.parquet
326,2025-03-04,1630059,Grasberg Findorffschule,True,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH,de:VBN:630:,de:VBN:630,630,False,False,,False,0304-1630059#!ADD!#IVU-Regio#,IVU-Regio,DEVIATION_OF_SCHEDULED,2025-03-04T12:19:00+01:00,Tarmstedt Schulzentrum KGS,de:03357:90041::1,2025-03-04T12:33:00+01:00,Grasberg Findorffschule,de:03356:31703::2,True,out/parquet/prod/zusatz_2025_03_04.parquet

### Auswertung Matrix nach Verlauf Zeitpunkt der Meldung

In [36]:
df_matrix = rt.cursor.sql("""select m.operatingDay::date, m.lineShortName, m.journeyId, v.index, 
                          m.stationName, m.scheduleDeparture,m.delay_minutes_arrival, m.delay_minutes_departure, m.timestamp, v.arr_del, v.dep_del
                from matrix m
                left join verlauf v on 
                          m.operatingDay = v.operday and 
                          m.lineShortName = v.lineshortname and 
                          m.journeyId = v.fnr and 
                          m.stationName = v.station_name
                where stop_cancelled = false
              and m.lineShortName = 'RS3'
              order by  m.operatingDay, m.externalLineId, m.journeyId, v.index,  m.timestamp 
              
              -- limit 20""").df()

In [37]:
auswahl_linien = '630|670|N68|N63|N67'
df_zusatz = rt.cursor.sql(f"""
                select datum::date as datum, lineshort,lineid ,fnr,  vu 
                from zusatz 
                where                       

                    lineid SIMILAR TO 'de:VBN:.*({auswahl_linien}).*' and 
                    -- and vu like 'Reisedienst von Rahden%' 
                    datum::date >= (current_date - interval 30 day)
                group by all 
                order by lineshort, fnr """).df()

df_zusatz

#rt.cursor.sql(f"""select * from zusatz where lineid  SIMILAR TO 'de:VBN:.*({auswahl_linien}).*' and datum::date >= (current_date - interval 30 day)""").df()

,datum,lineshort,lineid,fnr,vu
0,2025-02-14,630,de:VBN:630:,1630050,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
1,2025-02-17,630,de:VBN:630:,1630050,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
2,2025-02-17,630,de:VBN:630:,1630054,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
3,2025-02-28,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
4,2025-02-25,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
5,2025-02-27,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
6,2025-02-13,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
7,2025-02-06,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
8,2025-02-12,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
9,2025-03-03,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
10,2025-03-04,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
11,2025-02-10,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
12,2025-02-19,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
13,2025-02-05,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
14,2025-02-17,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
15,2025-02-14,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
16,2025-02-18,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
17,2025-02-20,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
18,2025-02-11,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
19,2025-02-24,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
20,2025-02-26,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
21,2025-02-21,630,de:VBN:630:,1630059,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
22,2025-02-22,630,de:VBN:630:,1630126,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
23,2025-02-16,630,de:VBN:630:,1630226,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
24,2025-02-23,630,de:VBN:630:,1630226,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
25,2025-02-18,670,de:VBN:670:,1670011,Eisenbahnen und Verkehrsbetriebe Elbe-Weser GmbH
26,2025-02-15,N68,de:VBN:N68:1,1068021,Weser-Ems-Bus Betrieb Bremen
27,2025-02-15,N68,de:VBN:N68:1,1068024,Weser-Ems-Bus Betrieb Bremen

In [38]:
rt.cursor.sql("select min(datum )::date as min_date, max(datum)::date as amx_date, count(*) as anzahl from fahrten")

┌────────────┬────────────┬─────────┐
│  min_date  │  amx_date  │ anzahl  │
│    date    │    date    │  int64  │
├────────────┼────────────┼─────────┤
│ 2024-08-29 │ 2025-03-04 │ 2728046 │
└────────────┴────────────┴─────────┘

### Häufung von Fahrten ohne Echtzeit

In [39]:
df_fahrten_ohne_ez = rt.cursor.sql("""
              
                select datum::date as datum, ebene, lineshort , fnr, hasrealtime
               
                from vw_buendel 
                where datum >= (current_date - interval 30 day) and hasrealtime = false
                group by all
                order by ebene, lineshort, fnr
    
              """).df()

df_fahrten_ohne_ez_zusatz = df_fahrten_ohne_ez.merge(df_zusatz, left_on = ['datum', 'fnr'], right_on = ['datum', 'fnr'], how='left')
df_fahrten_ohne_ez_zusatz.query("~vu.isnull()") 

df_fahrten_ohne_ez_zusatz[['lineshort_x','datum','fnr']].groupby(['lineshort_x','fnr'], as_index=False)\
    .agg(datum_min=('datum', 'min'), datum_max=('datum', 'max'), count=('datum', 'count')).sort_values('count', ascending=False)\
    .to_excel('out/rt_fahrten_ohne_ez_zusatz.xlsx', index=False)

In [40]:
df_fahrten_ohne_ez_zusatz.query("~vu.isnull()")

Empty DataFrame
Columns: [datum, ebene, lineshort_x, fnr, hasRealtime, lineshort_y, lineid, vu]
Index: []

In [41]:
interval_auswertung = 21
df_fahrten_mit_nicht_vollstaendiger_echtzeit = rt.cursor.sql(f"""
            select * from 
                (select ebene, lineshort , fnr, count(*) as anz, count(*) filter (hasRealtime) as anz_rt, 
                    (anz - anz_rt) as f_ohne_rt ,round(anz_rt/anz,2) as quote,
                    max(datum::date) filter (hasRealtime) as letzte_lieferung_echtzeit
                from vw_buendel 
                where datum >= (current_date - interval {interval_auswertung} day)
                group by all
                order by ebene, lineshort, fnr)
            where f_ohne_rt > 1 and ebene in ('1+','1', '2') 
            order by f_ohne_rt desc                                                             
            """).df()

df_fahrten_mit_nicht_vollstaendiger_echtzeit

,ebene,lineshort,fnr,anz,anz_rt,f_ohne_rt,quote,letzte_lieferung_echtzeit
0,1,450,6450109,15,12,3,0.80,2025-03-04
1,1,450,6450073,15,12,3,0.80,2025-03-04
2,1,440,6440103,15,13,2,0.87,2025-02-28
3,1,450,6450133,15,13,2,0.87,2025-03-04
4,1,450,6450726,3,1,2,0.33,2025-02-16
5,1,450,6450020,15,13,2,0.87,2025-03-04
6,2,460,6460055,15,13,2,0.87,2025-03-04
7,2,460,6460056,15,13,2,0.87,2025-03-04
8,1,440,6440127,15,13,2,0.87,2025-02-28
9,1,440,6440128,15,13,2,0.87,2025-02-28
10,1,450,6450055,15,13,2,0.87,2025-03-04
11,1,450,6450068,15,13,2,0.87,2025-03-04
12,1,450,6450080,15,13,2,0.87,2025-03-04
13,1,450,6450005,15,13,2,0.87,2025-03-04
14,2,460,6460068,15,13,2,0.87,2025-03-04
15,1,450,6450097,6,4,2,0.67,2025-02-27
16,1,450,6450116,15,13,2,0.87,2025-03-04

In [42]:
xl = 'out/nicht_vollstaendig.xlsx'
sn01 = '01 fahrten_rt_kl_100_roz'
sn02 = '02 zusatzfahrten'
sn03 = '03 ohne ez merge zusatz'

with pd.ExcelWriter(xl, engine='openpyxl') as writer: 
    df_fahrten_mit_nicht_vollstaendiger_echtzeit.to_excel(writer, index=False, sheet_name=sn01)
    writer.book[sn01].freeze_panes = 'A2'
    writer.book[sn01].auto_filter.ref='A:H'

    df_zusatz.to_excel(writer, index=False, sheet_name=sn02)
    writer.book[sn02].freeze_panes = 'A2'
    writer.book[sn02].auto_filter.ref='A:H'

    df_fahrten_ohne_ez_zusatz.to_excel(writer, index=False, sheet_name=sn03)
    writer.book[sn03].freeze_panes = 'A2'
    writer.book[sn03].auto_filter.ref='A:H'

In [43]:
q = rt.cursor.sql("""
                   (select 
                    datum::date as datum, ebene, lineshort, lineid_short, count(*) anz,
                    count(*) filter (hasRealtime) anz_rt, round(anz_rt/ anz,2) anteil_rt, 
                    max(datum) filter (hasRealtime) letzte_lieferung
                    from vw_buendel 
                    where datum >= date_trunc('month', (date_trunc('month',current_date) - interval 1 day)::date)
                    and datum <= (date_trunc('month',current_date) - interval 1 day)::date
                  
                    group by all

                    order by datum::date)
                  """)
#q.filter("lineshort in ('S35', '350')") #mit filter einfache Abfragen

q

┌────────────┬─────────┬───────────┬──────────────┬───────┬────────┬───────────┬─────────────────────┐
│   datum    │  ebene  │ lineshort │ lineid_short │  anz  │ anz_rt │ anteil_rt │  letzte_lieferung   │
│    date    │ varchar │  varchar  │   varchar    │ int64 │ int64  │  double   │    timestamp_ns     │
├────────────┼─────────┼───────────┼──────────────┼───────┼────────┼───────────┼─────────────────────┤
│ 2025-02-01 │ 1       │ 440       │ de:VBN:440   │    34 │     34 │       1.0 │ 2025-02-01 00:00:00 │
│ 2025-02-01 │ 2       │ 460       │ de:VBN:460   │    12 │      7 │      0.58 │ 2025-02-01 00:00:00 │
│ 2025-02-01 │ 1       │ 450       │ de:VBN:450   │    14 │     14 │       1.0 │ 2025-02-01 00:00:00 │
│ 2025-02-02 │ 1       │ 450       │ de:VBN:450   │    10 │     10 │       1.0 │ 2025-02-02 00:00:00 │
│ 2025-02-02 │ 1       │ 440       │ de:VBN:440   │    26 │     26 │       1.0 │ 2025-02-02 00:00:00 │
│ 2025-02-03 │ 1       │ 440       │ de:VBN:440   │    48 │     45 │      0.94 │ 2025-02-03 00:00:00 │
│ 2025-02-03 │ 3       │ 431       │ de:VBN:431   │     7 │      7 │       1.0 │ 2025-02-03 00:00:00 │
│ 2025-02-03 │ 1       │ 450       │ de:VBN:450   │    32 │     29 │      0.91 │ 2025-02-03 00:00:00 │
│ 2025-02-03 │ 2       │ 460       │ de:VBN:460   │    16 │     15 │      0.94 │ 2025-02-03 00:00:00 │
│ 2025-02-03 │ 3       │ 455       │ de:VBN:455   │     2 │      0 │       0.0 │ NULL                │
│     ·      │ ·       │  ·        │     ·        │     · │      · │        ·  │  ·                  │
│     ·      │ ·       │  ·        │     ·        │     · │      · │        ·  │  ·                  │
│     ·      │ ·       │  ·        │     ·        │     · │      · │        ·  │  ·                  │
│ 2025-02-28 │ 3       │ 452       │ de:VBN:452   │    11 │     11 │       1.0 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 432       │ de:VBN:432   │    19 │     17 │      0.89 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 448       │ de:VBN:448   │     5 │      3 │       0.6 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 455       │ de:VBN:455   │    14 │     13 │      0.93 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 459       │ de:VBN:459   │    15 │      5 │      0.33 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 1       │ 450       │ de:VBN:450   │    43 │     41 │      0.95 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 446       │ de:VBN:446   │     7 │      7 │       1.0 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 463       │ de:VBN:463   │    16 │     16 │       1.0 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 431       │ de:VBN:431   │    18 │     16 │      0.89 │ 2025-02-28 00:00:00 │
│ 2025-02-28 │ 3       │ 447       │ de:VBN:447   │     5 │      4 │       0.8 │ 2025-02-28 00:00:00 │
├────────────┴─────────┴───────────┴──────────────┴───────┴────────┴───────────┴─────────────────────┤
│ 318 rows (20 shown)                                                                      8 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [44]:
#Abfrage für den letzten Monat
q_pivot_lm = rt.cursor.sql("""
                    pivot (select 
                            datum::date as datum, ebene, lineshort, lineid_short, count(*) anz,
                            count(*) filter (hasRealtime) anz_rt, round(anz_rt/ anz,2) anteil_rt
                        from vw_buendel 
                        where datum >= date_trunc('month', (date_trunc('month',current_date) - interval 1 day)::date)
                            and datum <= (date_trunc('month',current_date) - interval 1 day)::date
                        group by all
                        )
                    on datum
                    using sum(anteil_rt)
                    group by lineshort, ebene
                    order by ebene, lineshort""")

q_pivot_lm.df().fillna('-')

,lineshort,ebene,2025-02-01,2025-02-02,2025-02-03,2025-02-04,2025-02-05,2025-02-06,2025-02-07,2025-02-08,2025-02-09,2025-02-10,2025-02-11,2025-02-12,2025-02-13,2025-02-14,2025-02-15,2025-02-16,2025-02-17,2025-02-18,2025-02-19,2025-02-20,2025-02-21,2025-02-22,2025-02-23,2025-02-24,2025-02-25,2025-02-26,2025-02-27,2025-02-28
0,440,1,1.0,1.0,0.94,1.0,1.00,1.00,0.88,0.97,0.92,0.96,1.00,0.92,1.00,1.00,1.0,1.0,1.00,1.00,1.00,1.00,1.00,1.0,1.0,1.00,1.00,1.00,1.00,1.00
1,450,1,1.0,1.0,0.91,1.0,0.89,0.95,0.88,1.0,1.0,0.93,0.86,0.95,0.84,0.95,1.0,1.0,1.00,0.84,0.91,0.84,0.93,1.0,0.9,1.00,1.00,1.00,0.95,0.95
2,460,2,0.58,-,0.94,1.0,1.00,0.85,0.90,1.0,-,0.60,0.95,0.85,0.75,0.95,0.92,-,1.00,1.00,1.00,1.00,1.00,1.0,-,1.00,1.00,1.00,0.90,1.00
3,431,3,-,-,1.0,1.0,0.78,0.83,0.78,-,-,0.83,0.94,0.83,0.78,0.94,-,-,0.94,0.94,0.94,0.89,0.89,-,-,1.00,1.00,1.00,0.94,0.89
4,432,3,-,-,-,-,0.74,0.58,0.68,-,-,0.63,0.89,0.89,0.84,0.95,-,-,0.89,0.89,0.89,0.95,0.89,-,-,0.89,0.89,0.89,0.89,0.89
5,446,3,-,-,-,-,0.57,0.57,0.71,-,-,0.86,0.86,0.71,0.71,0.86,-,-,1.00,0.86,0.86,0.86,0.86,-,-,1.00,1.00,1.00,1.00,1.00
6,447,3,-,-,-,-,0.67,0.50,0.40,-,-,1.00,0.67,0.83,0.67,0.60,-,-,1.00,1.00,0.83,0.83,1.00,-,-,1.00,1.00,0.83,0.83,0.80
7,448,3,-,-,-,-,0.80,0.60,0.60,-,-,0.80,1.00,1.00,1.00,0.80,-,-,0.80,0.80,0.80,1.00,0.80,-,-,1.00,1.00,0.80,1.00,0.60
8,451,3,-,-,-,-,0.62,0.43,0.67,-,-,0.76,0.76,0.81,0.67,0.67,-,-,0.81,0.86,0.71,0.76,0.81,-,-,0.76,0.95,0.81,0.86,0.90
9,452,3,-,-,-,-,0.54,0.69,0.82,-,-,0.85,0.92,0.77,0.77,0.91,-,-,1.00,1.00,0.85,0.85,1.00,-,-,0.92,0.92,0.92,0.92,1.00
10,455,3,-,-,0.0,0.0,0.47,0.60,0.71,-,-,0.87,1.00,0.87,0.93,0.86,-,-,1.00,1.00,1.00,0.93,0.93,-,-,0.93,0.93,0.93,0.93,0.93
11,458,3,-,-,-,-,0.48,0.64,0.64,-,-,0.96,0.92,1.00,0.88,0.91,-,-,0.96,1.00,1.00,1.00,0.95,-,-,1.00,1.00,1.00,1.00,0.91
12,459,3,-,-,-,-,0.33,0.33,0.27,-,-,0.72,0.72,0.72,0.61,0.27,-,-,0.72,0.72,0.72,0.39,0.53,-,-,0.72,0.72,0.72,0.72,0.33
13,461,3,-,-,-,-,0.50,0.60,0.78,-,-,0.70,0.70,0.90,0.80,0.78,-,-,0.80,0.90,0.90,0.90,0.78,-,-,0.90,0.80,0.90,0.80,0.89
14,462,3,-,-,-,-,1.00,0.67,1.00,-,-,0.33,0.33,1.00,1.00,1.00,-,-,1.00,1.00,1.00,1.00,1.00,-,-,1.00,1.00,1.00,1.00,1.00
15,463,3,-,-,-,-,0.53,0.47,0.81,-,-,0.82,0.82,0.88,0.76,0.69,-,-,0.82,1.00,1.00,1.00,1.00,-,-,1.00,1.00,1.00,0.94,1.00

## Ausgabe je Bündel als html / xlsx

### Erstellen der sortierten Bündelliste

In [45]:
list_buendel = sorted(rt.cursor.sql("select distinct buendel from linien where buendel not in ('nahsh')").df()['buendel'].to_list())

In [46]:
#Zellformatierung CSS
cell_hover = {  # for row hover use <tr> instead of <td>
    'selector': 'td:hover',
    'props': [('background-color', '#ffffb3')]
}
index_names = {
    'selector': '.index_name',
    'props': 'font-style: italic; color: darkgrey; font-weight:normal; font-family: sans-serif; font-size: 15px;'
}
headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: #FFFFFF; color: #000000; font-family: sans-serif; font-size: 15px;text-orientation: upright;'
}

td = {'selector' : 'td', 'props': 'text-align:right; font-family: sans-serif; font-size: 14px;'}

In [47]:
for b in list_buendel[8:9]:
    print(b, b.replace(' ', '_').lower(), replace_german_special_characters(b).replace(' ', '_').lower())

DH Südwest dh_südwest dh_suedwest

In [48]:
date_style = NamedStyle(name="date_style", number_format="YYYY-MM-DD")
eine_nachkomma = NamedStyle(name = 'eine_nachkomma', number_format= '#,##0.0')
zwei_nachkomma = NamedStyle(name = 'eine_nachkomma', number_format= '#,##0.00')

In [49]:
func_proz = lambda s: str(int((1-s) * 1000)/10) + '%' if str(int(s)) != '-1' else '-'
func_date = lambda s: s.dt.strftime('%m/%d/%Y')

interval_auswertung = 21

date_style = NamedStyle(name="date_style", number_format="YYYY-MM-DD")
eine_nachkomma = NamedStyle(name = 'eine_nachkomma', number_format= '#,##0.0')
zwei_nachkomma = NamedStyle(name = 'eine_nachkomma', number_format= '#,##0.00')

for b in list_buendel:
    print(b, b.replace(' ', '_').lower(), replace_german_special_characters(b).replace(' ', '_').lower())

    rt.create_vw_buendel(b)
    rt.create_vw_buendel_verlauf(buendel=b)
    rt.cal_rel(36)
    #Abfrage für die letzten 30 Tage
    q_pivot_lm = rt.cursor.sql(f"""
                        pivot (select 
                                datum::date as datum, ebene, lineshort, lineid_short, count(*) anz,
                                count(*) filter (realtimeHasEverBeenReported ) anz_rt, round(anz_rt/ anz,2) anteil_rt
                            from vw_buendel 
                            where datum >= (current_date - interval {interval_auswertung} day)
                            group by all
                            )
                        on datum
                        using sum(anteil_rt)
                        group by lineshort, ebene
                        order by ebene, lineshort""")
    
    #Liste der Fahrten ohne Echtzeit die häufiger als 1 mal vorkommen
    df_fahrten_mit_nicht_vollstaendiger_echtzeit = rt.cursor.sql(f"""
                select * from 
                    (select ebene, lineshort , fnr, count(*) as anz, count(*) filter (hasRealtime) as anz_ez, 
                    (anz - anz_ez) as fahrten_ohne_ez ,round(anz_ez/anz,2) as quote,
                    max(datum::date) filter (realtimeHasEverBeenReported ) as letzte_lieferung_echtzeit
                    from vw_buendel 
                    where datum >= (current_date - interval {interval_auswertung} day)
                    group by all
                    order by ebene, lineshort, fnr)
                where fahrten_ohne_ez > 1 and ebene in ('1+','1', '2','Nacht') 
                    order by fahrten_ohne_ez desc                                                             
                
                """).df()
    
    df_fahrten_ohne_ez = rt.cursor.sql(f"""              
                select datum::date as datum, ebene, lineshort , fnr, hasrealtime               
                from vw_buendel 
                where datum >= (current_date - interval {interval_auswertung} day) and realtimeHasEverBeenReported  = false
                group by all
                order by ebene, lineshort, fnr
    
              """).df()
    
    df_fahrten_gesamt = rt.cursor.sql(f"""              
                select *               
                from vw_buendel 
                where datum >= (current_date - interval {interval_auswertung} day) 
                order by ebene, lineshort, fnr
    
              """).df()
    
    html_zusatz_table = 'html/pre_zusatz.html'
    df_fahrten_ohne_ez_zusatz = df_fahrten_ohne_ez.merge(df_zusatz, left_on = ['datum', 'fnr'], right_on = ['datum', 'fnr'], how='left')
    df_fahrten_ohne_ez_zusatz.query("~vu.isnull()").to_html(html_zusatz_table, index=False)

    html_pre_table = 'html/pre_table.html'
    df_fahrten_mit_nicht_vollstaendiger_echtzeit.to_html(html_pre_table, index=False)

    html_pre_pivot = 'html/pre_pivot.html'
    q_pivot_lm.df().style.background_gradient(cmap="RdYlGn", axis = None,  vmin=0.5, vmax=1).highlight_null(color='white')\
        .format( precision=2, na_rep='-', thousands=" ")\
        .highlight_null(color='white')\
        .set_table_styles([index_names, headers, td])\
        .to_html(html_pre_pivot)
    
    # Save the HTML table to a file (optional)   
    with open(html_pre_pivot, 'r') as file:
        html_pre_pivot = file.read()
    
    # Load the HTML page template
    with open('html/template.html', 'r') as file:
        html_template = file.read()

    # Insert the HTML table into the template
    title = f"Echtzeitquote Bündel {b} je Linie erstellt: {dt.datetime.now().strftime('%d.%m.%Y %H:%M')}" 
    html_page = html_template.replace('{{ html_pivot }}', html_pre_pivot).replace('{{ html_title }}', title)

    if df_fahrten_mit_nicht_vollstaendiger_echtzeit.shape[0] > 0:
        html_page = html_page.replace('{{ html_table }}', df_fahrten_mit_nicht_vollstaendiger_echtzeit.to_html(index=False))
    else:
        html_page = html_page.replace('{{ html_table }}', "Keine Häufung Fahrten ohne Echtzeit")

    if df_fahrten_ohne_ez_zusatz.query("~vu.isnull()").shape[0] > 0:
        html_page = html_page.replace('{{ html_table_zusatz }}', df_fahrten_ohne_ez_zusatz.query("~vu.isnull()").to_html(index=False))
    else:
        html_page = html_page.replace('{{ html_table_zusatz }}', "Keine Zusatzfahrten mit gleicher Fahrtnummer")

    # Save the combined HTML page to a file
    html_combined = f"/var/www/rt_archiv/buendel/rt_{replace_german_special_characters(b).replace(' ', '_').lower()}.html"


    with open(html_combined, 'w') as file:
        file.write(html_page)


    #Ausgabe der wichtigen Ergebnisse als Excel
    xl = f"buendel_stat/{replace_german_special_characters(b).replace(' ', '_').lower()}_stat.xlsx"

    sn00 = '01 hilfe'
    sn01 = '02 statistik ebene'
    sn02 = '03 statistik pivot'
    sn03 = '04 fahrten gesamt'
    sn04 = '05 verlauf' #nicht im Stadtverkehr

    with pd.ExcelWriter(xl, engine='openpyxl') as writer:
        writer.book.add_named_style(date_style)

        #02 Statistik Ebene
        rt.cal_rel(36)
        df_vorfaelle = rt.cursor.sql("from cal_rel").df().merge(rt.df_vorfaelle_echtzeit(36), on = 'datum', how='left')
        df_vorfaelle.to_excel(writer, index=False, sheet_name=sn01)
        writer.book[sn01].freeze_panes = 'A2'
        writer.book[sn01].auto_filter.ref=f'A1:H{df_vorfaelle.shape[0]+1}'
        for row in writer.book[sn01].iter_rows(min_row=2, min_col=1, max_col=1):
                for cell in row:
                    cell.style = date_style

        for row in writer.book[sn01].iter_rows(min_row=2, min_col=7, max_col=7):
                for cell in row:
                    cell.style = zwei_nachkomma
        writer.book[sn01][f"H{df_vorfaelle.shape[0]+3}"] = f"=SUBTOTAL(9, H2:H{df_vorfaelle.shape[0]+1})"
        writer.book[sn01].column_dimensions['A'].width = 15
        # Add a three-color scale

        writer.book[sn01].conditional_formatting.add(f'G1:G{df_vorfaelle.shape[0]+1}',
                            ColorScaleRule(start_type='num', start_value=0.0, start_color='AA0000',
                            mid_type='num', mid_value=0.5, mid_color='FFFF00',
                            end_type='num', end_value=1.0, end_color='00AA00')
                             )

        #Statistik Pivot
        q_pivot_lm.df().to_excel(writer, index=True, sheet_name=sn02)
        writer.book[sn02].freeze_panes = 'A2'
        writer.book[sn02].auto_filter.ref='A:H'

        df_fahrten_gesamt.to_excel(writer, index=False, sheet_name=sn03)
        writer.book[sn03].freeze_panes = 'A2'
        writer.book[sn03].auto_filter.ref='A:N'
        writer.book[sn03].column_dimensions['A'].width = 15
        for row in writer.book[sn03].iter_rows(min_row=2, min_col=1, max_col=1):
                for cell in row:
                    cell.style = date_style

        #Verlauf nicht im Stadtverkehr wegen Datenmenge
        if b not in ('HB Bus', 'HB Tram', 'BHV', 'DEL', 'OL Stadt'):

            rt.cursor.sql("""from vw_buendel_verlauf""").df().to_excel(writer, index=False, sheet_name=sn04)
            writer.book[sn04].freeze_panes = 'A2'
            writer.book[sn04].auto_filter.ref='A:J'
            writer.book[sn04].column_dimensions['A'].width = 15
            writer.book[sn04].column_dimensions['F'].width = 30
            for row in writer.book[sn04].iter_rows(min_row=2, min_col=1, max_col=1):
                for cell in row:
                    cell.style = date_style

    # Öffnen des Workbooks und Anwenden der Formatierung
    wb = openpyxl.load_workbook(xl)

    #Erstellen des Hilfeblattes an erster Position
    wb.create_sheet(sn00, index=0)
    sheet = wb[sn00]
    sheet['A1'] = f"Erstellt: {dt.datetime.now().strftime('%Y-%m-%d %H:%M')}"
    sheet['A2'] =  "Erläuterung der Werte in der Tabelle"
    sheet['A3'] = f"Blatt {sn01} enthält die Echtzeitquote der Ebenen des Bündels {b} für die letzten {interval_auswertung} Tage"
    sheet['A4'] = f"Blatt {sn02} enthält die Echtzeitquote der Linien des Bündels {b} für die letzten {interval_auswertung} Tage"
    sheet['A5'] = f"Blatt {sn03} filterbare Liste der Fahrten {b} für die letzten {interval_auswertung} Tage"

    wb.save(xl)

AM Ost am_ost am_ost
AM Süd am_süd am_sued
AM West am_west am_west
BHV bhv bhv
DEL del del
DH Nordost dh_nordost dh_nordost
DH Nordwest dh_nordwest dh_nordwest
DH Südost dh_südost dh_suedost
DH Südwest dh_südwest dh_suedwest
HB Bus hb_bus hb_bus
HB Tram hb_tram hb_tram
OHZ Mitte ohz_mitte ohz_mitte
OHZ Ost ohz_ost ohz_ost
OHZ West ohz_west ohz_west
OL Nord ol_nord ol_nord
OL Stadt ol_stadt ol_stadt
OL Südost ol_südost ol_suedost
OL West ol_west ol_west
RBVBN rbvbn rbvbn
REKREUZ rekreuz rekreuz
RSB rsb rsb
TN 2 CUX tn_2_cux tn_2_cux
TN 5 CUX tn_5_cux tn_5_cux
TN 6 CUX tn_6_cux tn_6_cux
TN ROW Mitte tn_row_mitte tn_row_mitte
TN ROW Süd 3 tn_row_süd_3 tn_row_sued_3
VER Nord ver_nord ver_nord
VER Ost ver_ost ver_ost
VER Südwest ver_südwest ver_suedwest
WM Nord wm_nord wm_nord
WM Süd wm_süd wm_sued

In [53]:
#Ausgabe der wichtigen Ergebnisse als Excel
xl = "buendel_stat/uebersicht_stat.xlsx"

sn01 = '01 vormonat'
sn02 = '02 akt monat'

with pd.ExcelWriter(xl, engine='openpyxl') as writer:
    writer.book.add_named_style(date_style)
    rt.stat_monat(1).to_excel(writer, index=False, sheet_name=sn01)
    writer.book[sn01].freeze_panes = 'A2'
    writer.book[sn01].auto_filter.ref='A:H'
    rt.stat_monat(0).to_excel(writer, index=False, sheet_name=sn02)
    writer.book[sn02].freeze_panes = 'A2'
    writer.book[sn02].auto_filter.ref='A:H'

    for row in writer.book[sn01].iter_rows(min_row=2, min_col=1, max_col=1):
                for cell in row:
                    cell.style = date_style

    writer.book[sn01].column_dimensions['A'].width = 15

    for row in writer.book[sn02].iter_rows(min_row=2, min_col=1, max_col=1):
            for cell in row:
                cell.style = date_style
    writer.book[sn02].column_dimensions['A'].width = 15

shutil.copyfile(xl, '/var/www/rt_archiv/uebersicht_stat.xlsx')

'/var/www/rt_archiv/uebersicht_stat.xlsx'

### Upload nach Redmine

In [54]:
list_excel = glob.glob('buendel_stat/*.xlsx')
list_redmine = pd.read_csv('input/folder_vms.csv', sep=';', quotechar="'")['buen'].to_list()
df_redmine  = pd.read_csv('input/folder_vms.csv', sep=';', quotechar="'")

for b in list_buendel:
    b_clean = replace_german_special_characters(b).replace(' ', '_').lower()
    folder_file_name = os.path.join('buendel_stat', f"{b_clean}_stat.xlsx") 
    file_name =  f"{b_clean}_stat.xlsx"

    shutil.copyfile(folder_file_name, f'/var/www/rt_archiv/{file_name}')

    if b_clean not in list_redmine:
        print(f"not in {b_clean}")
    
    else:
        print(f"{b} in {b_clean}")
        project_url = df_redmine.query(f"buen == '{b_clean}'").reset_index().at[0, 'project_url']
        folder_id = df_redmine.query(f"buen == '{b_clean}'").reset_index().at[0, 'folder_id']

        delete_upload_dmsf(project_url=project_url, folder_id=folder_id, file_name=file_name, folder_file_name=folder_file_name)
        logging.info(f"{folder_file_name} hochgeladen")

AM Ost in am_ost
https://vms.zvbn.de/projects/steuerung-ammerland-ost_nn/dmsf.xml?folder_id=2718
id 31476
<Response [200]>
https://vms.zvbn.de/projects/steuerung-ammerland-ost_nn/dmsf/upload.xml?filename=am_ost_stat.xlsx
token 82622.3297429256f75449181f3d3505b69ee654add4aaa66a4a673aa5f36dbe089ca9
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>2718</folder_id>
      <uploaded_file>
        <name>am_ost_stat.xlsx</name>
        <title>am_ost_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82622.3297429256f75449181f3d3505b69ee654add4aaa66a4a673aa5f36dbe089ca9</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-ammerland-ost_nn/dmsf/commit.xml
<Response [200]>
not in am_sued
AM West in am_west
https://vms.zvbn.de/projects/steuerung-ammerland-west/dmsf.xml?folder_id=1459
id 31477
<Response [200]>
https://vms.zvbn.de/projects/steuerung-ammerland-west/dmsf/upload.xml?filename=am_west_stat.xlsx
token 82623.460a541e3ad5d9d61f1f04db5bb482f3be5e44aacfc63945369baf67e7047ca5
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1459</folder_id>
      <uploaded_file>
        <name>am_west_stat.xlsx</name>
        <title>am_west_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82623.460a541e3ad5d9d61f1f04db5bb482f3be5e44aacfc63945369baf67e7047ca5</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-ammerland-west/dmsf/commit.xml
<Response [200]>
not in bhv
not in del
DH Nordost in dh_nordost
https://vms.zvbn.de/projects/steuerung-diepholz-nordost/dmsf.xml?folder_id=1460
id 31478
<Response [200]>
https://vms.zvbn.de/projects/steuerung-diepholz-nordost/dmsf/upload.xml?filename=dh_nordost_stat.xlsx
token 82624.29fb2dab4c6889b4ab3781412381b8c9987ad3ca66688a47b9ed7ef6f0c18b3a
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1460</folder_id>
      <uploaded_file>
        <name>dh_nordost_stat.xlsx</name>
        <title>dh_nordost_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82624.29fb2dab4c6889b4ab3781412381b8c9987ad3ca66688a47b9ed7ef6f0c18b3a</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-diepholz-nordost/dmsf/commit.xml
<Response [200]>
DH Nordwest in dh_nordwest
https://vms.zvbn.de/projects/steuerung-diepholz-nordwest/dmsf.xml?folder_id=1461
id 31479
<Response [200]>
https://vms.zvbn.de/projects/steuerung-diepholz-nordwest/dmsf/upload.xml?filename=dh_nordwest_stat.xlsx
token 82625.2f06b21cb456cf697663f2984769c64d8aaa1f6af838f7a65de1c27da6f04e07
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1461</folder_id>
      <uploaded_file>
        <name>dh_nordwest_stat.xlsx</name>
        <title>dh_nordwest_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82625.2f06b21cb456cf697663f2984769c64d8aaa1f6af838f7a65de1c27da6f04e07</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-diepholz-nordwest/dmsf/commit.xml
<Response [200]>
DH Südost in dh_suedost
https://vms.zvbn.de/projects/steuerung-diepholz-suedost/dmsf.xml?folder_id=1462
id 31480
<Response [200]>
https://vms.zvbn.de/projects/steuerung-diepholz-suedost/dmsf/upload.xml?filename=dh_suedost_stat.xlsx
token 82626.031766002a8ae06d0ae70868be0c2082d04f8f64bb236524e7b06d8e219762c4
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1462</folder_id>
      <uploaded_file>
        <name>dh_suedost_stat.xlsx</name>
        <title>dh_suedost_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82626.031766002a8ae06d0ae70868be0c2082d04f8f64bb236524e7b06d8e219762c4</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-diepholz-suedost/dmsf/commit.xml
<Response [200]>
DH Südwest in dh_suedwest
https://vms.zvbn.de/projects/steuerung-diepholz-suedwest/dmsf.xml?folder_id=1463
id 31481
<Response [200]>
https://vms.zvbn.de/projects/steuerung-diepholz-suedwest/dmsf/upload.xml?filename=dh_suedwest_stat.xlsx
token 82627.da6773a143dec10d66f96ce73b7ed0dc2cdc33f167b9395e788f6003e320e00e
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1463</folder_id>
      <uploaded_file>
        <name>dh_suedwest_stat.xlsx</name>
        <title>dh_suedwest_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82627.da6773a143dec10d66f96ce73b7ed0dc2cdc33f167b9395e788f6003e320e00e</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-diepholz-suedwest/dmsf/commit.xml
<Response [200]>
not in hb_bus
not in hb_tram
OHZ Mitte in ohz_mitte
https://vms.zvbn.de/projects/steuerung-osterholz-mitte-west/dmsf.xml?folder_id=1464
id 31482
<Response [200]>
https://vms.zvbn.de/projects/steuerung-osterholz-mitte-west/dmsf/upload.xml?filename=ohz_mitte_stat.xlsx
token 82628.185ceb48a2e1fb54bf70486b3d55b346402b228a6767e8baaeed04d0d3d3a73a
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1464</folder_id>
      <uploaded_file>
        <name>ohz_mitte_stat.xlsx</name>
        <title>ohz_mitte_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82628.185ceb48a2e1fb54bf70486b3d55b346402b228a6767e8baaeed04d0d3d3a73a</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-osterholz-mitte-west/dmsf/commit.xml
<Response [200]>
OHZ Ost in ohz_ost
https://vms.zvbn.de/projects/steuerung-osterholz-ost/dmsf.xml?folder_id=1457
id 31483
<Response [200]>
https://vms.zvbn.de/projects/steuerung-osterholz-ost/dmsf/upload.xml?filename=ohz_ost_stat.xlsx
token 82629.21f7a72b92e4554211152129c1e521774322df98adb6e9531ec8c1ee8a70eba3
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1457</folder_id>
      <uploaded_file>
        <name>ohz_ost_stat.xlsx</name>
        <title>ohz_ost_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82629.21f7a72b92e4554211152129c1e521774322df98adb6e9531ec8c1ee8a70eba3</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-osterholz-ost/dmsf/commit.xml
<Response [200]>
OHZ West in ohz_west
https://vms.zvbn.de/projects/steuerung-ohz-west-uebergang-von-rahden/dmsf.xml?folder_id=3005
id 31484
<Response [200]>
https://vms.zvbn.de/projects/steuerung-ohz-west-uebergang-von-rahden/dmsf/upload.xml?filename=ohz_west_stat.xlsx
token 82630.4d12b21f012cbcdfed0a5fa8c26bc9fb193f29044fb3f98c9d43e4110c15b74e
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>3005</folder_id>
      <uploaded_file>
        <name>ohz_west_stat.xlsx</name>
        <title>ohz_west_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82630.4d12b21f012cbcdfed0a5fa8c26bc9fb193f29044fb3f98c9d43e4110c15b74e</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-ohz-west-uebergang-von-rahden/dmsf/commit.xml
<Response [200]>
OL Nord in ol_nord
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-nord/dmsf.xml?folder_id=1465
id 31485
<Response [200]>
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-nord/dmsf/upload.xml?filename=ol_nord_stat.xlsx
token 82631.da766bfcfd684c74ff274d0466e373a3fe36900d1e6d3ec30cffe3309f08dfee
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1465</folder_id>
      <uploaded_file>
        <name>ol_nord_stat.xlsx</name>
        <title>ol_nord_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82631.da766bfcfd684c74ff274d0466e373a3fe36900d1e6d3ec30cffe3309f08dfee</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-nord/dmsf/commit.xml
<Response [200]>
not in ol_stadt
OL Südost in ol_suedost
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-suedost/dmsf.xml?folder_id=1471
id 31486
<Response [200]>
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-suedost/dmsf/upload.xml?filename=ol_suedost_stat.xlsx
token 82632.6d5f7687b8ab6238cc0024e05e8602db5c213f568f7ceb54d98a4a305fe5c08c
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1471</folder_id>
      <uploaded_file>
        <name>ol_suedost_stat.xlsx</name>
        <title>ol_suedost_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82632.6d5f7687b8ab6238cc0024e05e8602db5c213f568f7ceb54d98a4a305fe5c08c</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-suedost/dmsf/commit.xml
<Response [200]>
OL West in ol_west
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-west/dmsf.xml?folder_id=1472
id 31487
<Response [200]>
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-west/dmsf/upload.xml?filename=ol_west_stat.xlsx
token 82633.e976bcd2c1e6de2e56daa9f94c64bebc038405d7809617c481d032553ef22a4d
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1472</folder_id>
      <uploaded_file>
        <name>ol_west_stat.xlsx</name>
        <title>ol_west_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82633.e976bcd2c1e6de2e56daa9f94c64bebc038405d7809617c481d032553ef22a4d</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-landkreis-oldenburg-west/dmsf/commit.xml
<Response [200]>
not in rbvbn
not in rekreuz
not in rsb
not in tn_2_cux
not in tn_5_cux
not in tn_6_cux
not in tn_row_mitte
not in tn_row_sued_3
VER Nord in ver_nord
https://vms.zvbn.de/projects/steuerung-verden-nord-vonau/dmsf.xml?folder_id=3030
id 31488
<Response [200]>
https://vms.zvbn.de/projects/steuerung-verden-nord-vonau/dmsf/upload.xml?filename=ver_nord_stat.xlsx
token 82634.8deb9ce32803eca29a01df3d02d2dec38345f7a569dfeae4e838cd55918ee942
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>3030</folder_id>
      <uploaded_file>
        <name>ver_nord_stat.xlsx</name>
        <title>ver_nord_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82634.8deb9ce32803eca29a01df3d02d2dec38345f7a569dfeae4e838cd55918ee942</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-verden-nord-vonau/dmsf/commit.xml
<Response [200]>
VER Ost in ver_ost
https://vms.zvbn.de/projects/steuerung-verden-ost/dmsf.xml?folder_id=1467
id 31489
<Response [200]>
https://vms.zvbn.de/projects/steuerung-verden-ost/dmsf/upload.xml?filename=ver_ost_stat.xlsx
token 82635.0ecd7243768de8215fb7d9f9cf1a8a5be475a4489524d879e4586a5b0b677cb3
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1467</folder_id>
      <uploaded_file>
        <name>ver_ost_stat.xlsx</name>
        <title>ver_ost_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82635.0ecd7243768de8215fb7d9f9cf1a8a5be475a4489524d879e4586a5b0b677cb3</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-verden-ost/dmsf/commit.xml
<Response [200]>
VER Südwest in ver_suedwest
https://vms.zvbn.de/projects/steuerung-verden-sued/dmsf.xml?folder_id=1468
id 31490
<Response [200]>
https://vms.zvbn.de/projects/steuerung-verden-sued/dmsf/upload.xml?filename=ver_suedwest_stat.xlsx
token 82636.0daf0a791f1e123edaebb0a97175e4ff9d6a9259e4f26c1f85990cf80bfac01c
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1468</folder_id>
      <uploaded_file>
        <name>ver_suedwest_stat.xlsx</name>
        <title>ver_suedwest_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82636.0daf0a791f1e123edaebb0a97175e4ff9d6a9259e4f26c1f85990cf80bfac01c</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-verden-sued/dmsf/commit.xml
<Response [200]>
WM Nord in wm_nord
https://vms.zvbn.de/projects/steuerung-wesermarsch-nord/dmsf.xml?folder_id=1469
id 31491
<Response [200]>
https://vms.zvbn.de/projects/steuerung-wesermarsch-nord/dmsf/upload.xml?filename=wm_nord_stat.xlsx
token 82637.827e83a951aa94268287a71586b918d3cf19b19573140ae370b27b63153c0c25
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1469</folder_id>
      <uploaded_file>
        <name>wm_nord_stat.xlsx</name>
        <title>wm_nord_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82637.827e83a951aa94268287a71586b918d3cf19b19573140ae370b27b63153c0c25</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-wesermarsch-nord/dmsf/commit.xml
<Response [200]>
WM Süd in wm_sued
https://vms.zvbn.de/projects/steuerung-wesermarsch-sued/dmsf.xml?folder_id=1470
id 31492
<Response [200]>
https://vms.zvbn.de/projects/steuerung-wesermarsch-sued/dmsf/upload.xml?filename=wm_sued_stat.xlsx
token 82638.21e9cee1e30fca4056f6d6c319e93d968263f68de27174dc7e276ad87326dfbb
 <?xml version="1.0" encoding="utf-8" ?>
    <attachments>
      <folder_id>1470</folder_id>
      <uploaded_file>
        <name>wm_sued_stat.xlsx</name>
        <title>wm_sued_stat.xlsx</title>
        <description>REST API</description>
        <version>3</version> <!-- It must be 3 (Custom version) -->
        <custom_version_major>1</custom_version_major> <!-- Major version -->
        <custom_version_minor>0</custom_version_minor>
        <comment>From API</comment>
        <!-- For an automatic version: -->
        <version/>
        <token>82638.21e9cee1e30fca4056f6d6c319e93d968263f68de27174dc7e276ad87326dfbb</token>
      </uploaded_file>
    </attachments>
https://vms.zvbn.de/projects/steuerung-wesermarsch-sued/dmsf/commit.xml
<Response [200]>

In [55]:
logging.info(f"Anzahl Fahrten gesamt {rt.anzahl_fahrten()}")

In [56]:
rt.verbindung_schliessen()

Verbindung zur DB geschlossen